server:
  port: 7001
  servlet:
    context-path: /coupon_template

spring:
  application:
    name: nacos-client-coupon-template
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: none
    properties:
      hibernate.show_sql: true
      hibernate.formate_sql: true
    open-in-view: false
  datasource:
    url: jdbc:mysql://192.168.56.101:3306/coupon_swarm?useSSL=false&useUnicode=true&characterEncoding=UTF-8&serverTimezone=GMT&allowPublicKeyRetrieval=true
    username: root
    password: VvkGNLf@NhG8
    type: com.zaxxer.hikari.HikariDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    hikari:
      maximum-pool-size: 8
      minimum-idle: 4
      idle-timeout: 30000
      connection-timeout: 30000
      max-lifetime: 45000
      auto-commit: true
      pool-name: CouponHikariCp
  redis:
    database: 0
    host: 192.168.56.101
    port: 6379
    timeout: 10000
    password: '123456:'
  cloud:
    nacos:
      discovery:
        server-addr: http://192.168.56.101:8848/
    sentinel: #Sentinel Dashboard通信地址
      transport:
        dashboard: 192.168.56.101:8080
      eager: true #取消控制台懒加载
dubbo:
  application:
    # 不要与实例的名称相同
    name: dubbo-client-coupon-template
  protocol:
    name: dubbo
    port: 20880
  registry:
    address: nacos://192.168.56.101:8848
logging:
  level:
    org.example.coupon: debug