server:
  port: 7003
  servlet:
    context-path: /coupon_settlement

spring:
  application:
    name: nacos-client-coupon-settlement
  cloud:
    nacos:
      discovery:
        server-addr: http://192.168.56.101:8848/

logging:
  level:
    org.example.coupon: debug