spring:
  application:
    name: coupon-zuul
  cloud:
    nacos:
      discovery:
        server-addr: http://192.168.56.101:8848/
server:
  port: 9000

zuul:
  #整体应用前缀
  prefix: /cloud
  routes:
    #优惠券模板微服务路由配置定义
    template:
      path: /coupon_template/**
      #对应spring.application.name
      serviceId: nacos-client-coupon-template
      #是否跳过前缀进行转发
      strip-prefix: false
  host:
    connect-timeout-millis: 15000
    socket-timeout-millis: 60000

ribbon:
  ConnectTimeout: 15000
  ReadTimeout: 15000